### ISSUE TITLE
Guide conflicts with ButterManager wiki

### ISSUE THREAD

**Issue by malonn23** [egara/arch-btrfs-installation#10]
This guide says to set up the filesystem and subvolumes a certain way.
```
Main Volume
|
----Subvolume (/<name>)
|
--------Subvolume (/<name>/<subname>)
|
--------Subvolume (/<name>/<subname>)
|
----Subvolume (/<snaps>)
```
The wiki says for GRUB integration, it must be:
```
Main Volume
|
----Subvolume (/<name>)
|
----Subvolume (/<name>/)
|
----Subvolume (/<snaps>)
```
I'm confused.  Can you help me understand the right way to set this thing up?  Is the wiki dated?  The guide dated?

**Comment by egara** [comment]
Hi @malonn23 and thank you very much for your feedback.

You are right, the layout is different in both sources but this is the key part of the ButterManager wiki:

```
For the purpose of this documentation, we are going to suppose that we have installed Manjaro using a manual partitioning with this requirements:

    Only one disk: sda
    Only one partition in the disk: sda1
    sda1 has been formatted using btrfs
    The mount point selected for this partition is /

After the installation of the operating system, the subvolumes automatically created are two (@ and @home) as you can see in the screenshot below:
```

As you can see, this is only an example of an automatic layout created after installing Manjaro using BTRFS as filesystem. The important thing here is to understand how we can manage those subvolumes with ButterManager and, overall, to have another subvolume for storing snapshots at volume level just as it is described in both sources.

This subvolume will be used to store all the snapshots created. Using ButterManager you will be able to define all the snapshots that will be created on demand when you want or during the system upgrade process.

I hope this help. Does it make sense to you? Feel free to ask any more questions :)

**Comment by malonn23** [comment]
Yes, @egara, it makes sense now.  I was reading up on the Arch Wiki and, with your help, understand how the wiki and guide differ.  I'm new to btrfs, so there's some new concepts for me to digest.  One is a flat layout, the other is a nested layout.  As long as the snapshots is at the top level, it's all good.  That's my understanding.  Thanks for the response.
