### ISSUE TITLE
manually rollback

### ISSUE THREAD

**Issue by QAQddbest** [egara/arch-btrfs-installation#3]
Thanks for your project!

I wonder how can I rollback the rootvol when I make every messy?

When I try to `mv` the backup in _snapshots to _active/rootvol, It tells me that it's a Read-only ***.
When I `btrfs subvolume delete` the subvolume of rootvol, the system went to hell... XD

Help needed. Thanks.

**Comment by egara** [comment]
Hi @QAQddbest and thank you very much for your kind words.

The process to rollback rootvol is:
- Boot the system using a Live CD
- Mount the BTRFS volume (f.i. sudo mount -o subvol=/ /dev/sda1 /mnt) (in this example, the BTRFS volume is in /dev/sda1)
- Now, you will have every subvolume under /mnt. cd to this directory
- Move root vol: sudo mv /mnt/_active/rootvol /mnt/_active/rootvol_old
- Create a new rw snapshot of the desired snapshot you want to restore on _active. F.i.: sudo btrfs subvolume snapshot /mnt/_snapshots/root_20201015 /mnt/_active/rootvol
- Unmount everything: sudo unmount /mnt
- Restart the system and you should boot on the snapshot you created before
- If everything is fine, remember to remove rootvol_old snapshot.

If you want a GUI tool to do all this in a more convenient way, you can try this other project I have: https://github.com/egara/buttermanager

Please, read the README file and the Wiki of the project to see all the details and configuration of the tool to do all this just with a simple click :)

Best wishes,

Eloy

**Comment by QAQddbest** [comment]
It's very kind of u, @egara ! Thanks for your help! I forgot that snapshoot is a subvolume too so that it counld be snapshot too XD.

I got it, thanks again.
